version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - WEAVIATE_HOST=weaviate
      - PPLX_API_KEY=${PPLX_API_KEY}
    depends_on:
      - redis
      - weaviate

  weaviate:
    image: semitechnologies/weaviate:1.24.1
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    volumes:
      - weaviate_data:/var/lib/weaviate

  redis:
    image: redis:7.2-alpine
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  weaviate_data:
  redis_data: 